# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5200c56fb21a531b58dd47d2c5a1d2c831bf91b8e2d1a641b8c5b947f12db175e36b958d2c9e04a99fbaeb08767d4d197492c7e9844b8a9066d8a68baf1bba

test:
  secret_key_base: 1550baa60c3823ac3dccbfc4c8353f1d70d9f4c2121ab9a518440069f813b3d8beab312b92718b7c360171e802488106554887ad5513c6bb944e3e617c0b792a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
